export const userFriends = [
    {
        name: 'Stefan',
        lastName: 'Hadzhiev',
        isOnline: true,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'Hristo ',
        lastName: 'Karamanliev',
        isOnline: false,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'Hristo',
        lastName: 'Gergov',
        isOnline: false,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'UniqueNameOne',
        lastName: 'One',
        isOnline: false,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'UniqueNameTwo',
        lastName: 'Two',
        isOnline: true,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'UniqueNameThree',
        lastName: 'Three',
        isOnline: true,
        lastSeen: '',
    },
    {
        name: 'UniqueNameFour',
        lastName: 'Four',
        isOnline: false,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'Test',
        lastName: 'Five',
        isOnline: false,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'Test',
        lastName: 'Six',
        isOnline: false,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'Test',
        lastName: 'Seven',
        isOnline: false,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'Test',
        lastName: 'Eight',
        isOnline: false,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'Test',
        lastName: 'Nine',
        isOnline: false,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'Test',
        lastName: 'Ten',
        isOnline: false,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'Test',
        lastName: 'Eleven',
        isOnline: false,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'Test',
        lastName: 'Twelve',
        isOnline: false,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'Test',
        lastName: 'Thirteen',
        isOnline: false,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'Test',
        lastName: 'Fourteen',
        isOnline: false,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'Test',
        lastName: 'Fifteen',
        isOnline: false,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'Test',
        lastName: 'Sixteen',
        isOnline: false,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'Test',
        lastName: 'Seventeen',
        isOnline: false,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'Test',
        lastName: 'Eighteen',
        isOnline: false,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'Test',
        lastName: 'Nineteen',
        isOnline: false,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'Test',
        lastName: 'Twenty',
        isOnline: false,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
    {
        name: 'Test',
        lastName: 'Twentyone',
        isOnline: false,
        lastSeen: 'last seen yesterday at 3:30 PM',
    },
];
